const FETCH_ALL_STORIES = "FETCH_ALL_STORIES";
const CREATE_STORY = "CREATE_STORY";
const UPDATE_STORY = "UPDATE_STORY";
const DELETE_STORY = "DELETE_STORY";
//const FETCH_OWN_STORIES = "FETCH_OWN_STORIES"

export {
    FETCH_ALL_STORIES,
    CREATE_STORY,
    UPDATE_STORY,
    DELETE_STORY,
}

