const FETCH_ALL_STORIES = "FETCH_ALL_STORIES";
const CREATE_STORY = "CREATE_STORY";
const UPDATE_STORY = "UPDATE_STORY";
const DELETE_STORY = "DELETE_STORY";
//const FETCH_OWN_STORIES = "FETCH_OWN_STORIES"
const FETCH_USER = "FETCH_USER"
const LOGIN_USER = "LOGIN_USER"
const REGISTER_USER = "REGISTER_USER"
const LOGOUT_USER = "LOGOUT_USER"

export {
    FETCH_ALL_STORIES,
    CREATE_STORY,
    UPDATE_STORY,
    DELETE_STORY,
    FETCH_USER,
    LOGIN_USER,
    REGISTER_USER,
    LOGOUT_USER,
}

